import type { FileResult } from '../commands/lint.js';
import { OECD_STEPS, type OecdStep, type ScreenResult, type Severity } from '../risk/screen.js';
import { PROFILE, SCHEMA_VERSION } from './schemas.js';

/**
 * Self-contained HTML reports for lint and risk runs: a traffic light, the
 * findings as tables, and the data provenance - the document a compliance
 * team forwards to a supplier or files for an audit. No external assets.
 */

export interface ReportMeta {
  version: string;
  generatedAt: string; // ISO timestamp, injected by the caller for testability
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #F4F5F4; color: #1A1A1A; font-family: Outfit, -apple-system, 'Segoe UI', Roboto, sans-serif; }
  .page { max-width: 860px; margin: 0 auto; padding: 48px 32px 64px; }
  .brand { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 40px; }
  .brand .lockup { font-weight: 700; font-size: 13px; letter-spacing: 0.06em; text-transform: uppercase; line-height: 1.25; color: #0D1117; }
  .brand .tool { font-family: 'Space Mono', Menlo, monospace; font-size: 13px; color: #555; }
  h1 { font-size: 28px; font-weight: 800; color: #253749; letter-spacing: -0.01em; margin-bottom: 6px; }
  .meta { font-size: 13px; color: #555; margin-bottom: 28px; line-height: 1.6; }
  .verdict { border-radius: 3px; padding: 14px 20px; font-size: 16px; font-weight: 700; color: #fff; margin-bottom: 32px; }
  .verdict.pass { background: #16a34a; }
  .verdict.fail { background: #dc2626; }
  .verdict.warn { background: #b45309; }
  h2 { font-size: 17px; font-weight: 700; color: #253749; margin: 28px 0 10px; }
  .file-ok { color: #16a34a; font-weight: 700; }
  .file-fail { color: #dc2626; font-weight: 700; }
  table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid rgba(0,0,0,0.12); font-size: 13.5px; }
  th { text-align: left; padding: 8px 12px; background: #E0E7EE; color: #253749; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; }
  td { padding: 8px 12px; border-top: 1px solid rgba(0,0,0,0.08); vertical-align: top; line-height: 1.5; }
  td.ptr, td.mono { font-family: 'Space Mono', Menlo, monospace; font-size: 12.5px; white-space: nowrap; }
  .badge { display: inline-block; border-radius: 2px; padding: 2px 8px; font-size: 11px; font-weight: 700; letter-spacing: 0.06em; color: #fff; }
  .badge.high { background: #dc2626; }
  .badge.medium { background: #b45309; }
  .badge.info { background: #253749; }
  .evidence { color: #555; font-size: 12px; margin-top: 4px; }
  .nofindings { color: #555; font-size: 13.5px; padding: 4px 0 0 2px; }
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid rgba(0,0,0,0.12); font-size: 12px; color: #888; line-height: 1.7; }
`;

function shell(title: string, body: string, meta: ReportMeta): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${CSS}</style>
</head>
<body>
<div class="page">
  <div class="brand">
    <div class="lockup">Pangea<br>Intelligence</div>
    <div class="tool">dpp-lint ${esc(meta.version)}</div>
  </div>
${body}
  <footer>
    Generated by dpp-lint ${esc(meta.version)} on ${esc(meta.generatedAt)} |
    profile ${esc(PROFILE)}, data model ${esc(SCHEMA_VERSION)} |
    <a href="https://pangea-intelligence.eu" style="color:#253749">pangea-intelligence.eu</a><br>
    This report is a point-in-time technical check of the submitted data.
    It is not legal advice and does not replace an audit.
  </footer>
</div>
</body>
</html>
`;
}

export function renderLintReport(results: FileResult[], meta: ReportMeta): string {
  const failed = results.filter((r) => !r.valid);
  const verdict =
    failed.length === 0
      ? `<div class="verdict pass">PASS - all ${results.length} file(s) conform to the schema</div>`
      : `<div class="verdict fail">FAIL - ${failed.length} of ${results.length} file(s) with findings</div>`;

  const sections = results
    .map((r) => {
      const status = r.valid
        ? '<span class="file-ok">OK</span>'
        : `<span class="file-fail">FAIL</span>`;
      const moduleLabel = r.module ? ` <span style="color:#555">(${esc(r.module)})</span>` : '';
      let table = '';
      if (!r.valid) {
        const rows = r.errors
          .map((f) => {
            const din = f.dinChapter ? `DIN DKE SPEC 99100 ch. ${esc(f.dinChapter)}` : '';
            const name = f.preferredName ? esc(f.preferredName) : '';
            const ref = [name, din].filter(Boolean).join('<br>');
            return `<tr><td class="ptr">${esc(f.pointer === '' ? '/' : f.pointer)}</td><td>${esc(
              f.message
            )}</td><td>${ref}</td></tr>`;
          })
          .join('\n');
        table = `<table><thead><tr><th>Location</th><th>Finding</th><th>Reference</th></tr></thead><tbody>${rows}</tbody></table>`;
      }
      return `<h2>${status} ${esc(r.file)}${moduleLabel}</h2>\n${table}`;
    })
    .join('\n');

  const body = `
  <h1>Battery passport schema check</h1>
  <div class="meta">${results.length} file(s) validated against the official
  Battery Pass data model (DIN DKE SPEC 99100).</div>
  ${verdict}
  ${sections}`;
  return shell('dpp-lint schema check', body, meta);
}

export function renderRiskReport(
  input: {
    file: string;
    originsFile?: string;
    originsCount?: number;
    warnings: string[];
    result: ScreenResult;
  },
  meta: ReportMeta
): string {
  const { high, medium, info } = input.result.summary;
  const verdict =
    high > 0
      ? `<div class="verdict fail">${high} high / ${medium} medium / ${info} info - high-priority due-diligence findings</div>`
      : medium > 0
        ? `<div class="verdict warn">0 high / ${medium} medium / ${info} info - findings to resolve</div>`
        : `<div class="verdict pass">No high or medium findings (${info} informational)</div>`;

  const badge = (s: Severity) => `<span class="badge ${s}">${s.toUpperCase()}</span>`;

  const steps: OecdStep[] = [1, 2, 3, 4, 5];
  const sections = steps
    .map((step) => {
      const findings = input.result.findings.filter((f) => f.oecdStep === step);
      const heading = `<h2>OECD step ${step} - ${esc(OECD_STEPS[step])}</h2>`;
      if (findings.length === 0) return `${heading}<div class="nofindings">no findings</div>`;
      const rows = findings
        .map((f) => {
          const entry = f.evidence.entry ? ` ${JSON.stringify(f.evidence.entry)}` : '';
          return `<tr><td>${badge(f.severity)}</td><td class="mono">${esc(f.rule)}</td><td>${esc(
            f.message
          )}<div class="evidence">evidence: ${esc(f.evidence.dataset)}${esc(entry)}<br>ref: ${esc(
            f.reference
          )}</div></td></tr>`;
        })
        .join('\n');
      return `${heading}<table><thead><tr><th>Severity</th><th>Rule</th><th>Finding</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('\n');

  const warnings =
    input.warnings.length > 0
      ? `<div class="meta">Origins file warnings: ${input.warnings.map(esc).join('; ')}</div>`
      : '';

  const originsLine = input.originsFile
    ? `${esc(input.originsFile)} (${input.originsCount} entr${input.originsCount === 1 ? 'y' : 'ies'})`
    : 'none provided - CAHRA and smelter screening skipped';

  const body = `
  <h1>Raw material due-diligence screening</h1>
  <div class="meta">payload: ${esc(input.file)}<br>origins: ${originsLine}<br>
  Screening along the OECD five-step due-diligence framework (EU 2023/1542, Art. 48-52).</div>
  ${verdict}
  ${warnings}
  ${sections}`;
  return shell('dpp-lint risk screening', body, meta);
}
