#!/usr/bin/env node
// Extracts a property -> {preferredName, description, dinChapter, see}
// map from the vendored SAMM TTL models (BatteryPassDataModel 1.2.0).
//
// Findings from inspecting the TTL sources:
// - samm:see holds only generic URLs (schema.org, cas.org). It does NOT
//   contain DIN DKE SPEC 99100 chapter references.
// - The DIN chapter references live inside the samm:description text as
//   "DIN DKE Spec chapter reference: 6.1.2.2" (GeneralProductInformation,
//   MaterialComposition) or "DIN DKE Spec 99100 chapter reference: 6.4.2"
//   (SupplyChainDueDiligence). We extract them from there with a regex.
//
// Output: schemas/battery/1.2.0/din-map.json (checked-in generated artifact).
// Plain Node, no dependencies. Run: node scripts/extract-din-map.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const MODULES = [
  'GeneralProductInformation',
  'MaterialComposition',
  'SupplyChainDueDiligence',
  'CarbonFootprintForBatteries',
  'Circularity',
  'PerformanceAndDurability',
  'Labeling',
];

const DIN_CHAPTER_RE = /DIN DKE Spec(?:\s+99100)?\s+chapter reference:?\s*([0-9][0-9.]*[0-9]|[0-9])/i;

/**
 * Strips the stale boilerplate paragraph ("Copyright ... Circulor ... CC BY-NC 4.0")
 * that upstream left inside some Aspect-level samm:description literals. The
 * authoritative license of the data model is CC-BY-4.0 (file headers, SPDX ids,
 * upstream README since the 2025-10 license standardization); the embedded text
 * predates that and must not end up in our shipped din-map.json.
 */
function stripLicenseBoilerplate(s) {
  return s.replace(/\s*Copyright\s[\s\S]*$/u, '').trimEnd();
}

/** Unescapes a Turtle single-line string literal body. */
function unescapeTtl(s) {
  return s
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t')
    .replace(/\\r/g, '\r')
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
}

/** Matches a quoted @en literal for the given predicate inside a block. */
function literalEn(block, predicate) {
  const re = new RegExp(`${predicate}\\s+"((?:[^"\\\\]|\\\\.)*)"@en`);
  const m = block.match(re);
  return m ? unescapeTtl(m[1]) : undefined;
}

/**
 * Splits a TTL document into subject statements via a line-based scan.
 * The vendored files use the layout ":LocalName a <type> ;\n ... ." with
 * statement-terminating dots at end of line, and all string literals are
 * single-line (escaped \n), so this is sufficient. Not a general parser.
 */
function parseStatements(ttl) {
  const out = [];
  const lines = ttl.split(/\r?\n/);
  let current = null;
  for (const line of lines) {
    const startMatch = line.match(/^:([A-Za-z0-9_]+)\s+a\s+([A-Za-z0-9:_.-]+)/);
    if (startMatch && !current) {
      current = { name: startMatch[1], type: startMatch[2], body: line };
    } else if (current) {
      current.body += '\n' + line;
    }
    if (current && /(^|\s)\.\s*$/.test(line)) {
      out.push(current);
      current = null;
    }
  }
  return out;
}

const result = {
  _comment:
    'Generated by scripts/extract-din-map.mjs from ttl/*.ttl ' +
    '(BatteryPassDataModel 1.2.0, CC-BY-4.0, see NOTICE). Do not edit by hand. ' +
    'DIN chapter references are extracted from samm:description text; ' +
    'samm:see in the upstream models only carries generic URLs.',
  profile: 'battery',
  version: '1.2.0',
  modules: {},
};

let totalProps = 0;
let withChapter = 0;

for (const module of MODULES) {
  const ttl = readFileSync(path.join(root, 'ttl', `${module}.ttl`), 'utf8');
  const entries = {};

  for (const stmt of parseStatements(ttl)) {
    const { name, type, body } = stmt;
    const isProperty = /samm:Property\b/.test(type);
    const preferredName = literalEn(body, 'samm:preferredName');
    const rawDescription = literalEn(body, 'samm:description');
    const description = rawDescription ? stripLicenseBoilerplate(rawDescription) : rawDescription;
    const see = [...body.matchAll(/samm:see\s+<([^>]+)>/g)].map((m) => m[1]);
    if (!preferredName && !description && see.length === 0) continue;

    const entry = {};
    if (preferredName) entry.preferredName = preferredName;
    if (description) entry.description = description;
    if (see.length > 0) entry.see = see;
    if (description) {
      const chapter = description.match(DIN_CHAPTER_RE);
      if (chapter) {
        entry.dinChapter = chapter[1].replace(/\.$/, '');
        if (isProperty) withChapter += 1;
      }
    }
    entry.kind = isProperty ? 'property' : 'other';
    entries[name] = entry;
    if (isProperty) totalProps += 1;
  }

  result.modules[module] = entries;
}

const outFile = path.join(root, 'schemas', 'battery', '1.2.0', 'din-map.json');
writeFileSync(outFile, JSON.stringify(result, null, 2) + '\n', 'utf8');
console.log(
  `din-map.json written: ${Object.keys(result.modules).length} modules, ` +
    `${totalProps} properties (${withChapter} with a DIN DKE SPEC 99100 chapter reference)`
);
